version: '3.4'
services:
  dev:
    image: webpronl/reveal-md
    command: /slides slides.md --watch --port 8000
    ports: &ports
      - 8000:8000
      - 35729:35729
    volumes: &vol
      - ./:/slides

  static:
    image: webpronl/reveal-md
    command: /slides slides.md --static docs
    volumes: *vol
